# ▶변수 설정

# 종속변수 = '청소년 범죄 5대 범죄 비율'

### 2) 5대범죄 발생건수 (분자)
- 변수명 : total_teen_crime
- 데이터 : https://www.data.go.kr/data/3075889/fileData.do


In [ ]:
import pandas as pd

teen_crime_list = []

for year in range(12,22):
  index = "20" + str(year)
  teen_crime = pd.read_csv(f'청소년범죄_{year}.csv', header=0, encoding='euc-kr')
# 경찰서별로 데이터가 나와있기 때문에, 각 경찰서가 속한 '구'로 다시 인덱싱하는 작업입니다
  teen_crime['구'] = ['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구', '영등포구', '성동구', '동작구', '광진구', '은평구', '강북구', '금천구', '중랑구', '강남구', '관악구', '강서구', '강동구', '성북구', '구로구', '서초구', '양천구', '송파구', '노원구', '서초구', '은평구', '도봉구', '강남구']
  teen_crime = teen_crime.groupby('구').sum()
  teen_crime[index] = teen_crime.iloc[:, :5].sum(axis=1)
  teen_crime_list.append(teen_crime[index])
  
total_teen_crime = pd.concat(teen_crime_list,axis = 1)
total_teen_crime

<ipython-input-1-e05e8f250129>:10: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  teen_crime = teen_crime.groupby('구').sum()
<ipython-input-1-e05e8f250129>:10: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  teen_crime = teen_crime.groupby('구').sum()
<ipython-input-1-e05e8f250129>:10: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  teen_crime = teen_crime.groupby('구').sum()
<ipython-input-1-e05e8f250129>:10: FutureWarning: Th

2012  2013  2014  2015  2016  2017  2018  2019  2020   2021
구                                                                
강남구    448   354   313   342   341   310   233   276   290  284.0
강동구    508   384   385   394   360   254   358   362   320  239.0
강북구    704   434   458   362   385   311   223   237   173  158.0
강서구    859   662   514   608   525   501   333   410   297  288.0
관악구    562   509   463   351   395   416   350   321   246  185.0
광진구    756   541   430   352   337   327   317   318   182  152.0
구로구    601   521   320   460   355   330   304   348   237  152.0
금천구    645   387   261   273   219   276   179   146   108   87.0
노원구    700   717   624   605   584   524   362   330   244  179.0
도봉구    533   454   320   279   260   220   190   165   154   84.0
동대문구   548   346   232   302   209   257   207   244   162  114.0
동작구    346   407   265   247   182   290   252   195   154  141.0
마포구    476   334   266   245   333   310   339   243   205  170.0
서대문구   544   423   294   266   254   198   245   186   194  136.0
서초구    344   327   188   203   154   177   198   200   141  171.0
성동구    383   342   201   161   189   177   155    97   139   87.0
성북구    599   422   417   292   284   322   288   278   127  146.0
송파구    685   479   426   384   375   385   355   357   325  212.0
양천구    632   505   440   440   321   367   275   300   231  191.0
영등포구   481   425   340   336   243   248   267   300   237  121.0
용산구    337   196   201   169   134   156    92    63    74   72.0
은평구    806   572   441   392   483   394   573   398   310  266.0
종로구    280   241   137   115   169   104   105    77    72   39.0
중구     382   278   220   159   134    72    85    84    91   81.0
중랑구    731   607   401   370   382   350   250   301   184  161.0

In [ ]:
# 휴 세로로 다시 이어붙이기 성공...
total_teen_crime = total_teen_crime.stack().reset_index()
print(type(total_teen_crime))
total_teen_crime

<class 'pandas.core.frame.DataFrame'>


구 level_1      0
0    강남구    2012  448.0
1    강남구    2013  354.0
2    강남구    2014  313.0
3    강남구    2015  342.0
4    강남구    2016  341.0
..   ...     ...    ...
245  중랑구    2017  350.0
246  중랑구    2018  250.0
247  중랑구    2019  301.0
248  중랑구    2020  184.0
249  중랑구    2021  161.0

[250 rows x 3 columns]

In [ ]:
total_table = pd.DataFrame() # 종속변수!

total_table['teen_crime'] = total_teen_crime[0]
# 이런 식으로 total_table에 계속 데이터 쌓아가는 형식으로 전체 데이터를 준비하면 될 것 같아요!
print(type(total_table))
print(total_table)

<class 'pandas.core.frame.DataFrame'>
     teen_crime
0         448.0
1         354.0
2         313.0
3         342.0
4         341.0
..          ...
245       350.0
246       250.0
247       301.0
248       184.0
249       161.0

[250 rows x 1 columns]


In [ ]:
total_table.columns

Index(['teen_crime'], dtype='object')

# 독립변수1. 가정폭력 건수
- 변수명 : total_fam_viol  

- 데이터 :
https://www.data.go.kr/data/3075688/fileData.do?recommendDataYn=Y  

In [ ]:
fam_viol_list = []

for year in range(12,22):
  fam_viol = pd.read_csv(f'가정폭력_{year}.csv', header=0, encoding='euc-kr')
# '가정폭력 건수' 역시 경찰서별로 데이터가 나와있기 때문에, 각 경찰서가 속한 구로 다시 인덱싱하는 작업입니다 / fv = family_violence
  fam_viol['구'] = ['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구', '영등포구', '성동구', '동작구', '광진구', '은평구', '강북구', '금천구', '중랑구', '강남구', '관악구', '강서구', '강동구', '성북구', '구로구', '서초구', '양천구', '송파구', '노원구', '서초구', '은평구', '도봉구', '강남구']
  fam_viol = fam_viol.groupby('구').sum()
  fam_viol[f'20{str(year)}'] = fam_viol.iloc[:, :4].sum(axis=1)
  fam_viol_list.append(fam_viol[f'20{str(year)}'])

total_fam_viol = pd.concat(fam_viol_list,axis = 1)
total_fam_viol

<ipython-input-14-07b68f2c5850>:7: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  fam_viol = fam_viol.groupby('구').sum()
<ipython-input-14-07b68f2c5850>:7: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  fam_viol = fam_viol.groupby('구').sum()
<ipython-input-14-07b68f2c5850>:7: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  fam_viol = fam_viol.groupby('구').sum()
<ipython-input-14-07b68f2c5850>:7: FutureWarning: The default va

2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
구                                                               
강남구    282   634   509   910  1094   866   842  1219   895   940
강동구    396   837   683  1080  1218  1002   917  1160  1012  1000
강북구    192   522   675  1198  1289  1070  1011  1368   792   653
강서구    519   656   622  1571  1976  1820  1507  1627  1174  1333
관악구    248   498   708  1046  1121  1173   901  1045   905   895
광진구    299   417   622   714   828   750   737   852   644   819
구로구    306   585   715  1093  1192   884  1176  1192   777   910
금천구    276   447   646   714   978   895   587  1011   478   555
노원구    505   707   981  1273  1327  1285  1227  1820  1342  1657
도봉구    282   376   558   753   875   802   886  1085   819   930
동대문구   564   363   505   833  1001   870   853  1061   851   670
동작구    123   281   254   673   830   671   690  1070   758   627
마포구    298   434   561   887   880   782   665   929   550   556
서대문구   356   497   563   735   826   664   618   751   425   577
서초구    200   308   344   575   669   583   555  1091   714   642
성동구    137   260   366   699   741   708   693   830   581   496
성북구    297   507   639   971   968   715   948  1229   740   839
송파구    446   681   676  1429  1337  1406  1566  1426  1102  1330
양천구    296   729   813  1215  1318  1156  1087   943   644  1053
영등포구   351   507   499   864  1127   938  1091  1151   574   722
용산구    165   354   303   550   660   497   397   633   283   483
은평구    811   840  1017  1423  1567  1159   918  1520   933   932
종로구     99   203   258   410   443   231   262   416   238   240
중구     102   146   162   361   411   353   306   325   371   406
중랑구    234   580   648  1149  1315  1299  1281  1773   874   895

In [ ]:
# 휴 세로로 다시 이어붙이기 성공...
total_fam_viol = total_fam_viol.stack().reset_index()
print(type(total_fam_viol))
total_fam_viol

<class 'pandas.core.frame.DataFrame'>


구 level_1     0
0    강남구    2012   282
1    강남구    2013   634
2    강남구    2014   509
3    강남구    2015   910
4    강남구    2016  1094
..   ...     ...   ...
245  중랑구    2017  1299
246  중랑구    2018  1281
247  중랑구    2019  1773
248  중랑구    2020   874
249  중랑구    2021   895

[250 rows x 3 columns]

In [ ]:
total_table['Family_Violence'] = total_fam_viol[0]
total_table
# 전체 테이블에 독립변수1 추가

Teen_Crime  Family_Violence
0          41.5              282
1          33.7              634
2          29.5              509
3          32.6              910
4          33.8             1094
..          ...              ...
245        62.5             1299
246        47.2             1281
247        61.4             1773
248        40.0              874
249        36.6              895

[250 rows x 2 columns]

# 독립변수2. 가로등 수
- 변수명 : total_light_num

- 데이터: 
https://data.seoul.go.kr/dataList/261/S/2/datasetView.do 

In [ ]:
# 가로등 수는 바로 '구'별로 데이터가 되어있어서 groupby 작업 필요없이 그냥 잘 불러오기만 하면 될 것 같아요!
light_num_list = []

for year in range(12,22):
  col = 28*year - 307
  light_num = pd.read_csv('가로등_수.csv', skiprows=list(range(1, 11)), header=0, names=['구', '20'+str(year)], usecols=[1, col])
  light_num = light_num.sort_values(by='구', ascending=True)
  light_num.set_index('구', inplace=True)
  light_num_list.append(light_num)

total_light_num = pd.concat(light_num_list, axis = 1)
total_light_num

2012   2013   2014   2015   2016   2017   2018   2019   2020   2021
구                                                                         
강남구   12390  12292  12042  12184  13826  14193  14193  13788  14326  14351
강동구    6468   6950   7264   7232   7411   7891   7982   7477   7952   8126
강북구    4303   4336   4352   4360   4440   4445   4525   4339   4301   4308
강서구    6499   6871   6520   6540   6569   6691   6682   8919   9552   9994
관악구    5121   5160   5170   4964   4897   4895   4894   5304   5588   5789
광진구    4957   4927   4982   4981   4925   4852   4774   4616   4908   4944
구로구    6994   6918   7336   7365   7419   7413   7490   7529   8199   8270
금천구    4598   4668   4669   4736   5354   5369   5294   5496   5507   4945
노원구    8934   8944   8966   8745   9267   9308   9270   9510   9443   9573
도봉구    4420   4797   4388   4400   4405   4464   4471   4556   4584   4613
동대문구   7289   7377   7738   7890   8019   8096   8149   8211   8342   8359
동작구    5015   5087   5087   4641   5328   5483   5568   5656   6105   6019
마포구    7322   7312   7475   7428   7645   7941   8177   8313   8392   8696
서대문구   5563   5641   5705   5467   5667   5848   6075   6075   6245   5994
서초구   10591  10694  10920  11143  11622  11699  12691  12793  12588  12593
성동구    5884   5389   5532   5299   5712   5662   5780   6050   6266   6256
성북구    5283   5281   5306   5301   5288   5373   5301   5584   5744   5755
송파구   10348  10095   9351  11225  12054  12586  13263  13520  14184  14822
양천구    7346   7286   7277   7209   7206   7198   7833   7970   8583   8717
영등포구   8781   8810   9026   8679   9157   9209   9500   9278   9535   9653
용산구    6861   6816   6886   6977   7206   7291   7248   7637   7838   7838
은평구    8162   8125   8008   6835   6455   6554   6428   6369   6173   6275
종로구    8975   8975   8988   8988   8988   8986   9220   9265   8818   7947
중구     9380   9281   9200   8651   8621   8641   8694   8665   8550   8619
중랑구    5310   5297   5598   5392   5682   5698   5729   5731   6521   6877

In [ ]:
# 얘도 다시 세로로 ...
total_light_num = total_light_num.stack().reset_index()
print(type(total_light_num))
total_light_num

<class 'pandas.core.frame.DataFrame'>


구 level_1      0
0    강남구    2012  12390
1    강남구    2013  12292
2    강남구    2014  12042
3    강남구    2015  12184
4    강남구    2016  13826
..   ...     ...    ...
245  중랑구    2017   5698
246  중랑구    2018   5729
247  중랑구    2019   5731
248  중랑구    2020   6521
249  중랑구    2021   6877

[250 rows x 3 columns]

In [ ]:
total_table['Street_Light'] = total_light_num[0]
total_table

Teen_Crime  Family_Violence  Street_Light
0          41.5              282         12390
1          33.7              634         12292
2          29.5              509         12042
3          32.6              910         12184
4          33.8             1094         13826
..          ...              ...           ...
245        62.5             1299          5698
246        47.2             1281          5729
247        61.4             1773          5731
248        40.0              874          6521
249        36.6              895          6877

[250 rows x 3 columns]

# 독립변수3. 한부모가정 수
- 변수명 : total_one_parent

- 데이터 :
https://data.seoul.go.kr/dataList/437/S/2/datasetView.do

In [ ]:
# 정우님이 하신 방식대로 일단 해뒀습니다.
one_parent_list = []

# use_col 불규칙해서 반복문 사용 불가 = 그냥 일일이 지정함..
one_parent = pd.read_csv('한부모가정_수.csv', skiprows=[1,2,3,4], header=0, names=['구', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021'], usecols=[0,3,17,29,39,49,59,69,79,89,103])
one_parent = one_parent.sort_values(by='구', ascending=True)
one_parent.set_index('구', inplace=True)
one_parent_list.append(one_parent)

total_one_parent = pd.concat(one_parent_list, axis = 1)
print(type(total_one_parent))
total_one_parent

<class 'pandas.core.frame.DataFrame'>


2012  2013  2014  2015  2016  2017  2018  2019  2020  2021
구                                                               
강남구    555   600   719   663   320   294   254   190   129   102
강동구   1083  1175  1156   993   461   422   407   338   268   189
강북구   1615  1605  1626  1487   611   568   551   470   349   262
강서구   1707  1721  1852  1759   877   760   800   661   448   355
관악구   1162  1275  1353  1157   641   585   508   420   270   187
광진구   1238  1155  1189  1078   465   361   359   288   252   170
구로구   1183  1003   998   933   444   429   439   383   327   226
금천구   1072  1096  1038   898   412   367   369   324   246   188
노원구   1237  1580  1569  1500   728   638   590   477   339   216
도봉구   1149  1441  1469  1304   583   493   435   393   321   253
동대문구  1018  1033   984   937   389   352   313   270   208   169
동작구    937   948   911   821   381   315   247   193   148   104
마포구    762   759   774   708   427   373   333   265   202   171
서대문구   895   938   926   864   473   386   369   339   250   170
서초구    463   551   556   496   263   207   197   159   121    81
성동구    701   728   690   626   244   240   240   207   159   100
성북구   1285  1254  1238  1120   558   497   493   375   271   193
송파구   1164  1207  1279  1243   556   497   455   370   300   206
양천구   1414  1437  1377  1247   512   451   442   358   254   195
영등포구   688   679   658   579   245   213   191   185   154   113
용산구    323   467   436   438   185   188   176   169   116    85
은평구   1781  1845  1807  1690   696   593   516   492   366   240
종로구    312   367   356   333   187   159   154   140   114    96
중구     354   332   332   280   114   119   103    93    94    72
중랑구   2129  2273  2229  1998   783   670   649   576   434   311

In [ ]:
# 세로로 이어붙이는 작업 마찬가지로 진행..
total_one_parent = total_one_parent.stack().reset_index()
print(type(total_one_parent))
total_one_parent

<class 'pandas.core.frame.DataFrame'>


구 level_1    0
0    강남구    2012  555
1    강남구    2013  600
2    강남구    2014  719
3    강남구    2015  663
4    강남구    2016  320
..   ...     ...  ...
245  중랑구    2017  670
246  중랑구    2018  649
247  중랑구    2019  576
248  중랑구    2020  434
249  중랑구    2021  311

[250 rows x 3 columns]

In [ ]:
total_table['One_Parent'] = total_one_parent[0]
total_table

Teen_Crime  Family_Violence  Street_Light  One_Parent
0          41.5              282         12390         555
1          33.7              634         12292         600
2          29.5              509         12042         719
3          32.6              910         12184         663
4          33.8             1094         13826         320
..          ...              ...           ...         ...
245        62.5             1299          5698         670
246        47.2             1281          5729         649
247        61.4             1773          5731         576
248        40.0              874          6521         434
249        36.6              895          6877         311

[250 rows x 4 columns]

# 독립변수4. 파출소 수
- 변수명 : total_police_num

- 데이터 : 
https://data.seoul.go.kr/dataList/224/S/2/datasetView.do

In [ ]:
import pandas as pd

police_num = pd.read_csv('경찰서_수.csv', skiprows= [1,2,28], header=0 , usecols = list(range(1,62)))
police_num = police_num.sort_values(by='자치구별(2)', ascending=True)
police_num.set_index('자치구별(2)', inplace=True)
#police_num = pd.DataFrame(police_num).fillna(0)
police_num = police_num.replace("-",0)
police_num = police_num.replace("1",1)
police_num = police_num.replace("2",2)
total_police_num = pd.DataFrame()

for year in range(12,22):
  police_per_year = police_num.iloc[:, 6*year - 71 :6*year - 65]
  total_police_num[f'20_{str(year)}'] = police_per_year.sum(axis=1)
  #print(police_per_year)이걸로 오류 찾아냄 = str 인식 못하는 데이터 직접 수정함!

total_police_num

20_12  20_13  20_14  20_15  20_16  20_17  20_18  20_19  20_20  20_21
0      33     33     33     33     33     33     33     33     32     32
1      26     26     27     27     28     27     27     27     27     27
2      19     19     19     19     19     19     19     19     19     19
3      20     20     20     20     20     21     21     21     21     21
4      17     15     15     15     15     16     17     17     17     17
5      29     29     29     29     28     28     27     27     27     27
6      23     24     24     24     24     24     23     23     23     23
7      32     31     31     31     31     31     31     31     31     31
8      21     21     21     21     21     21     20     20     20     20
9      16     16     15     16     16     16     15     15     15     15
10     26     26     26     26     26     26     25     24     23     23
11     26     26     27     27     27     27     27     27     27     27
12     19     18     18     18     18     18     18     18     17     17
13     26     26     24     26     25     25     25     23     23     23
14     24     25     25     25     24     24     22     23     22     22
15     22     21     21     20     20     19     19     20     20     20
16     26     26     26     26     27     25     24     24     25     25
17     13     13     13     15     15     15     15     15     15     16
18     24     24     24     23     22     22     22     22     22     22
19     22     22     22     22     22     23     23     23     23     23
20     29     28     28     26     26     26     25     25     25     24
21     27     27     27     28     28     28     28     28     28     28
22     31     31     31     31     32     32     32     30     30     30
23     29     29     29     29     29     29     28     28     29     29
24     25     25     25     24     24     24     23     23     24     24

In [ ]:
# 세로로 이어붙이는 작업 마찬가지.
total_police_num = total_police_num.stack().reset_index()
print(type(total_police_num))
total_police_num

<class 'pandas.core.frame.DataFrame'>


level_0 level_1   0
0          0   20_12  33
1          0   20_13  33
2          0   20_14  33
3          0   20_15  33
4          0   20_16  33
..       ...     ...  ..
245       24   20_17  24
246       24   20_18  23
247       24   20_19  23
248       24   20_20  24
249       24   20_21  24

[250 rows x 3 columns]

In [ ]:
# 전체 테이블 최신화!
total_table['Police_Station'] = total_police_num[0]
total_table

Teen_Crime  Family_Violence  Street_Light  One_Parent  Police_Station
0          41.5              282         12390         555              33
1          33.7              634         12292         600              33
2          29.5              509         12042         719              33
3          32.6              910         12184         663              33
4          33.8             1094         13826         320              33
..          ...              ...           ...         ...             ...
245        62.5             1299          5698         670              24
246        47.2             1281          5729         649              23
247        61.4             1773          5731         576              23
248        40.0              874          6521         434              24
249        36.6              895          6877         311              24

[250 rows x 5 columns]

# 독립변수5. 기초수급자 수
- 변수명 : total_basic_num

[데이터]  
- 데이터는 아래에   
https://data.seoul.go.kr/dataList/10113/S/2/datasetView.do

[to do]  
- 구별로 2021~2012까지 10년치에 대해서 해주시면 될 거 같아요!

In [ ]:
import pandas as pd

basic_living_num_12 = pd.read_csv("기초수급_12.csv",skiprows= [0,1,2,3,4],names = ["구","2012"], usecols = [1,2])
basic_living_num_13_14 = pd.read_csv("기초수급_13_14.csv",skiprows= [0,1,2,3,4],names = ["2013","2014"], usecols = [2,13])
basic_living_num_15_19 = pd.read_csv("기초수급_15_19.csv",skiprows= [0,1,2,3,4,5],names = ["2015","2016","2017","2018","2019"], usecols = [2,13,24,35,46])
userows = [5, 24, 41, 59, 78, 95,111,129,151,166,182,203,221,237,255, 275,297,315,327,347,364,387,407,431,460]
skip_rows = list(set(range(482)) - set(userows))
basic_living_num_20_21 = pd.read_csv("기초수급_20_21.csv",skiprows= skip_rows,names = ["2020","2021"], usecols = [3,14])

total_basic_num = pd.concat([basic_living_num_12, basic_living_num_13_14, basic_living_num_15_19, basic_living_num_20_21], axis = 1)
total_basic_num.set_index('구', inplace=True)
total_basic_num.sort_index(inplace=True)
total_basic_num

2012   2013   2014   2015   2016   2017   2018   2019   2020   2021
구                                                                         
강남구    5122   5256   5797   6587   6915   6890   7208   8372   9820  10930
강북구    6263   6726   7156   8718   9993  10033  11125  12471  14116  15882
강서구   10263  10535  11040  12477  13757  13990  15432  17095  19877  22315
관악구    6580   6770   7044   8029   8771   9147  10371  11978  15417  17573
광진구    3240   3254   3448   4786   5096   5126   6102   6942   8475   9659
구로구    3785   3749   3971   5352   5666   5672   6107   7188   8534   9698
금천구    4683   4889   4853   5954   6263   6321   6737   7383   8372   9271
노원구   11814  12154  12561  14774  15384  15462  17022  18764  21151  22755
도봉구    3252   3561   3821   5986   6641   6934   7666   8367   9645  10867
동대문구   5844   6184   6460   8028   8278   8296   9280  10058  11452  12527
동작구    3614   3733   3901   4461   5227   5357   6375   7413   8840   9664
마포구    3852   3841   3924   4737   4882   4859   5550   6178   7195   7888
서대문구   3497   3754   3980   4897   5167   5292   6014   6574   7517   8525
서초구    1851   1986   2173   2811   3023   3102   3574   4030   4610   5062
성동구    3472   3561   3650   4699   4850   4889   5583   6123   7047   7607
성북구    5832   6300   6627   8072   8434   8290   8824   9665  10928  11964
송파구    3970   4216   4460   5856   6310   6306   6986   8154  10302  11923
송파구    3640   3719   3889   5520   5942   6189   7680   8890  10670  12048
양천구    4270   4295   4378   6434   6885   6923   8175   9506  11131  12368
영등포구   5340   5246   5138   5998   5808   5756   6394   7227   8557   9361
용산구    3319   3386   3525   4305   4421   4498   4910   5282   6219   6691
은평구    6096   6499   6800   9348  10045  10228  11876  13111  15455  16753
종로구    2323   2302   2338   2754   2792   2944   3109   3413   3851   4215
중구     2647   2602   2533   3021   3081   3102   3360   3671   4236   4732
중랑구    6135   6109   6428   9503  10044  10403  11818  13840  17378  19240

In [ ]:
# 세로로 이어붙이는 작업 마찬가지.
total_basic_num = total_basic_num.stack().reset_index()
print(type(total_basic_num))
total_basic_num

<class 'pandas.core.frame.DataFrame'>


구 level_1      0
0    강남구    2012   5122
1    강남구    2013   5256
2    강남구    2014   5797
3    강남구    2015   6587
4    강남구    2016   6915
..   ...     ...    ...
245  중랑구    2017  10403
246  중랑구    2018  11818
247  중랑구    2019  13840
248  중랑구    2020  17378
249  중랑구    2021  19240

[250 rows x 3 columns]

In [ ]:
# 전체 테이블 최신화!
total_table['Recipient_Basic'] = total_basic_num[0]
total_table

Teen_Crime  Family_Violence  Street_Light  One_Parent  Police_Station  \
0          41.5              282         12390         555              33   
1          33.7              634         12292         600              33   
2          29.5              509         12042         719              33   
3          32.6              910         12184         663              33   
4          33.8             1094         13826         320              33   
..          ...              ...           ...         ...             ...   
245        62.5             1299          5698         670              24   
246        47.2             1281          5729         649              23   
247        61.4             1773          5731         576              23   
248        40.0              874          6521         434              24   
249        36.6              895          6877         311              24   

     Recipient_Basic  
0               5122  
1               5256  
2               5797  
3               6587  
4               6915  
..               ...  
245            10403  
246            11818  
247            13840  
248            17378  
249            19240  

[250 rows x 6 columns]

In [ ]:
total_table.columns

Index(['Teen_Crime', 'Family_Violence', 'Street_Light', 'One_Parent',
       'Police_Station', 'Recipient_Basic', 'teen_crime_num'],
      dtype='object')

# ▶데이터 분포 & 상관성 확인

In [ ]:
total_table.info() # 결측치 없는 것 확인!

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Teen_Crime       250 non-null    float64
 1   Family_Violence  250 non-null    int64  
 2   Street_Light     250 non-null    int64  
 3   One_Parent       250 non-null    int64  
 4   Police_Station   250 non-null    int64  
 5   Recipient_Basic  250 non-null    int64  
 6   teen_crime_num   250 non-null    float64
dtypes: float64(2), int64(5)
memory usage: 13.8 KB


## 로그변환 (2차)

In [ ]:
import numpy as np

total_table['Teen_Crime'] = np.log1p(total_table['teen_crime']) # 종속변수!

#total_table['Street_Light'] = np.log1p(total_table['Street_Light'])

total_table['One_Parent'] = np.log1p(total_table['One_Parent'])

total_table['Recipient_Basic'] = np.log1p(total_table['Recipient_Basic'])

total_table.head(10)

Teen_Crime  Family_Violence  Street_Light  One_Parent  Police_Station  \
0    3.749504              282         12390    6.320768              33   
1    3.546740              634         12292    6.398595              33   
2    3.417727              509         12042    6.579251              33   
3    3.514526              910         12184    6.498282              33   
4    3.549617             1094         13826    5.771441              33   
5    3.496508              866         14193    5.686975              33   
6    3.261935              842         14193    5.541264              33   
7    3.433987             1219         13788    5.252273              33   
8    3.502550              895         14326    4.867534              32   
9    3.505557              940         14351    4.634729              32   

   Recipient_Basic  
0         8.541495  
1         8.567316  
2         8.665268  
3         8.793005  
4         8.841593  
5         8.837971  
6         8.883086  
7         9.032768  
8         9.192278  
9         9.299358

## 세트분할 (1차)

In [ ]:
from sklearn.model_selection import train_test_split
#train = total_table[['Family_Violence', 'Street_Light', 'One_Parent', 'Police_Station']].to_numpy() # 다중공선성 위험으로 인해 X5는 제외!
train = total_table[['Family_Violence', 'Street_Light', 'One_Parent', 'Police_Station', 'Recipient_Basic']].to_numpy() 
target = total_table['teen_crime'].to_numpy()
# input(X)과 target(Y) 데이터를 , 훈련/테스트 세트로 분리!
train_X, test_X, train_Y, test_Y = train_test_split(train, target, test_size=0.25)

# ▶스케일 전처리

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(train_X)
train_X_scaled = ss.transform(train_X) # 훈련세트 표준화
test_X_scaled = ss.transform(test_X) # 그에 맞게 테스트세트도 표준화!

In [ ]:
train_X_scaled[:5] # 상위 5개만 확인해봄!

array([[ 3.26434059, -0.30451524,  0.49630778, -0.85312566,  0.33074295],
       [ 1.04766722, -0.31080391, -0.08806011,  0.80008157,  0.6965733 ],
       [-0.59109742, -0.98536886, -0.92140165,  1.42003428,  3.84191087],
       [ 0.34766511, -1.00675035, -0.26295895, -1.47307837, -0.33940201],
       [ 0.33138599, -0.80760905, -0.55308526,  1.42003428,  2.01075042]])

# ▶모델링

# ①선형회귀 임시 모델링

In [ ]:
from sklearn.model_selection import cross_validate
from sklearn.linear_model import LinearRegression
import numpy as np

# 선형회귀 모델 생성
model_1 = LinearRegression()
scores = cross_validate(model_1, train_X_scaled, train_Y, return_train_score=True, n_jobs=-1)

# cross_validate로 교차검증을 통한 검증점수를 구해보자!
print('훈련점수:', np.mean(scores['train_score']), '검증점수:', np.mean(scores['test_score']))

훈련점수: 0.6227630648363844 검증점수: 0.5863926016272014


In [ ]:
 # 계수 출력
model_1.fit(train_X_scaled, train_Y)
print(model_1.coef_)
print(model_1.intercept_)

[ 20.38767857  19.36809942 121.84862577  -1.58854298 -12.8128203 ]
310.5401069518717


## 특성공학 (1차시도)

In [ ]:
from sklearn.preprocessing import PolynomialFeatures # 다항특성 변환기 클래스 불러오기

poly = PolynomialFeatures(degree=2, include_bias=False) # 절편을 위한 항은 빼고
poly.fit(train_X_scaled)
train_poly = poly.transform(train_X) # 훈련데이터 특성추가!

In [ ]:
poly.get_feature_names_out()

array(['x0', 'x1', 'x2', 'x3', 'x4', 'x0^2', 'x0 x1', 'x0 x2', 'x0 x3',
       'x0 x4', 'x1^2', 'x1 x2', 'x1 x3', 'x1 x4', 'x2^2', 'x2 x3',
       'x2 x4', 'x3^2', 'x3 x4', 'x4^2'], dtype=object)

In [ ]:
model_1.fit(train_poly, train_Y)  # 일단 훈련세트 성능이 급하니, 훈련세트만 해보자.
print(model_1.score(train_poly, train_Y))

0.7484769306017081


## 특성공학 (2차시도)

In [ ]:
poly2 = PolynomialFeatures(degree=3, include_bias=False) # 절편을 위한 항은 빼고
poly2.fit(train_X_scaled)
train_poly2 = poly2.transform(train_X_scaled) # 훈련데이터 특성추가!

In [ ]:
model_1.fit(train_poly2, train_Y)  # 일단 훈련세트 성능이 급하니, 훈련세트만 해보자.
print(model_1.score(train_poly2, train_Y))

0.8476637905862348


## 특성공학 (3차시도)

In [ ]:
poly3 = PolynomialFeatures(degree=4, include_bias=False) # 절편을 위한 항은 빼고
poly3.fit(train_X_scaled)
train_poly3 = poly3.transform(train_X_scaled) # 훈련데이터 특성추가!

In [ ]:
model_1.fit(train_poly3, train_Y)  # 일단 훈련세트 성능이 급하니, 훈련세트만 해보자.
print(model_1.score(train_poly3, train_Y))

0.9454974257556372


In [ ]:
# 오 꽤나 높아졌네? 검증점수도 확인해보자 그럼!
scores = cross_validate(model_1, train_poly3, train_Y, return_train_score=True, n_jobs=-1)

# cross_validate로 교차검증을 통한 검증점수를 구해보자!
print('훈련점수:', np.mean(scores['train_score']), '검증점수:', np.mean(scores['test_score']))
# 아이고 이거 봐...

훈련점수: 0.9774845714980893 검증점수: -76.43380507387198


## 릿지


In [ ]:
from sklearn.linear_model import Ridge # 릿지 규제(L1)

ridge = Ridge() # 릿지 모델 객체 생성 + alpha값은 기본값인 1로 적용됨
scores = cross_validate(ridge, train_poly3, train_Y, return_train_score=True, n_jobs=-1)

# cross_validate로 교차검증을 통한 검증점수를 구해보자!
print('훈련점수:', np.mean(scores['train_score']), '검증점수:', np.mean(scores['test_score']))

훈련점수: 0.938025903328289 검증점수: -0.7312671394251965


# ②SGD 임시 모델링

In [ ]:
from sklearn.linear_model import SGDRegressor

model_2 = SGDRegressor(max_iter=1000)
scores = cross_validate(model_2, train_X_scaled, train_Y, return_train_score=True, n_jobs=-1)

# cross_validate로 교차검증을 통한 검증점수를 구해보자!
print('훈련점수:', np.mean(scores['train_score']), '검증점수:', np.mean(scores['test_score']))

훈련점수: 0.6227533793875173 검증점수: 0.5864367129575419


# ③회귀트리 임시 모델링

In [ ]:
from sklearn.tree import DecisionTreeRegressor

# 회귀트리 모델 생성
model_3 = DecisionTreeRegressor()
scores = cross_validate(model_3, train_X_scaled, train_Y, return_train_score=True, n_jobs=-1)

# cross_validate로 교차검증을 통한 검증점수를 구해보자!
print('훈련점수:', np.mean(scores['train_score']), '검증점수:', np.mean(scores['test_score']))

훈련점수: 1.0 검증점수: 0.437581952364776


In [ ]:
model_3.fit(train_X_scaled, train_Y)
print(model_3.feature_importances_) # 특성중요도

[0.12944764 0.09473549 0.69081636 0.01660769 0.06839283]


그리드서치!

In [ ]:
from sklearn.model_selection import GridSearchCV

params ={'max_depth':[3, 5, 7, 9, 11], 'max_features':[2,3,4]} # 하이퍼파라미터 후보들 설정
gs3 = GridSearchCV(DecisionTreeRegressor(), params, cv=4, n_jobs=-1)

In [ ]:
gs3.fit(train_X_scaled, train_Y)

GridSearchCV(cv=4, estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'max_depth': [3, 5, 7, 9, 11],
                         'max_features': [2, 3, 4]})

In [ ]:
gs3.best_params_

{'max_depth': 9, 'max_features': 4}

In [ ]:
gs3_best = gs3.best_estimator_
# GridSearchCV에서는 그 파라미터로 학습한 최적의 모델을 반환해준다!
print(gs3_best.score(train_X_scaled, train_Y))
print(gs3_best.score(test_X_scaled, test_Y))

0.9930465318654637
0.588732093908666


In [ ]:
print(gs3_best.feature_importances_) # 특성중요도

[0.11976945 0.11133195 0.69400835 0.01407412 0.06081613]


# ④랜덤포레스트 회귀 임시 모델링

In [ ]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestRegressor
import numpy as np

# 랜덤포레스트 모델 생성
model_4 = RandomForestRegressor(oob_score=True, n_jobs=-1)
scores = cross_validate(model_4, train_X_scaled, train_Y, return_train_score=True, n_jobs=-1)

# cross_validate로 교차검증을 통한 검증점수를 구해보자!
print('훈련점수:', np.mean(scores['train_score']), '검증점수:', np.mean(scores['test_score']))

훈련점수: 0.9534730471551279 검증점수: 0.6867918034938397


In [ ]:
model_4.fit(train_X_scaled, train_Y)
print(model_4.feature_importances_) # 특성중요도

[0.11385626 0.07469684 0.70784898 0.03176816 0.07182977]


In [ ]:
print(model_4.oob_score_)

0.6905816516783361


그리드서치 

In [ ]:
from sklearn.model_selection import GridSearchCV

params ={'n_estimators':[300, 500, 700, 900, 1100], 'max_depth':[3, 5, 7, 9, 11], 'max_features':[2,3,4]} # 하이퍼파라미터 후보들 설정
gs4 = GridSearchCV(RandomForestRegressor(), params, cv=3, n_jobs=-1)

In [ ]:
gs4.fit(train_X_scaled, train_Y)

GridSearchCV(cv=3, estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'max_depth': [3, 5, 7, 9, 11],
                         'max_features': [2, 3, 4],
                         'n_estimators': [300, 500, 700, 900, 1100]})

In [ ]:
gs4.best_params_

{'max_depth': 9, 'max_features': 3, 'n_estimators': 300}

In [ ]:
gs4_best = gs4.best_estimator_
# GridSearchCV에서는 그 파라미터로 학습한 최적의 모델을 반환해준다!
print(gs4_best.score(train_X_scaled, train_Y))
print(gs4_best.score(test_X_scaled, test_Y))

0.9558292045973444
0.7619902255394596


In [ ]:
print(gs4_best.feature_importances_) # 특성중요도

[0.13119956 0.08586441 0.63830486 0.05736667 0.0872645 ]


# ⑤엑스트라트리 회귀 임시 모델링

In [ ]:
from sklearn.ensemble import ExtraTreesRegressor
# 이번엔 엑스트라트리 객체를 생성해서,
model_5 = ExtraTreesRegressor(n_jobs=-1)
scores = cross_validate(model_5, train_X_scaled, train_Y, return_train_score=True, n_jobs=-1)

# 마찬가지로 cross_validate로 교차검증을 수행해보면
print('훈련점수:', np.mean(scores['train_score']), '검증점수:', np.mean(scores['test_score']))

훈련점수: 0.9999999966843063 검증점수: 0.6988133755857351


In [ ]:
model_5.fit(train_X_scaled, train_Y)
print(model_5.feature_importances_) # 특성중요도

[0.12210506 0.075733   0.6699304  0.05632418 0.07590737]


그리드서치

In [ ]:
from sklearn.model_selection import GridSearchCV

params ={'n_estimators':[300, 500, 700, 900, 1100], 'max_depth':[3, 5, 7, 9, 11], 'max_features':[2,3,4]} # 하이퍼파라미터 후보들 설정
gs5 = GridSearchCV(ExtraTreesRegressor(), params, cv=5, n_jobs=-1)

In [ ]:
gs5.fit(train_X_scaled, train_Y)

GridSearchCV(cv=5, estimator=ExtraTreesRegressor(), n_jobs=-1,
             param_grid={'max_depth': [3, 5, 7, 9, 11],
                         'max_features': [2, 3, 4],
                         'n_estimators': [300, 500, 700, 900, 1100]})

In [ ]:
gs5.best_params_

{'max_depth': 11, 'max_features': 2, 'n_estimators': 1100}

In [ ]:
gs5_best = gs5.best_estimator_
# GridSearchCV에서는 그 파라미터로 학습한 최적의 모델을 반환해준다!
print(gs5_best.score(train_X_scaled, train_Y))
print(gs5_best.score(test_X_scaled, test_Y))

0.9836048786240675
0.7836130443218072


In [ ]:
print(gs5.cv_results_['mean_test_score']) # 앙상블이라서 weak model들이네..

[0.44490712 0.44119361 0.44195287 0.44706265 0.44730894 0.53284801
 0.52842834 0.53117933 0.53150051 0.53276325 0.57246592 0.57940612
 0.57715365 0.57412635 0.57854978 0.5938318  0.59183224 0.59399349
 0.58988273 0.59451586 0.63917765 0.63829753 0.63898146 0.63904794
 0.64328104 0.65094855 0.65636715 0.65632516 0.65485006 0.65477301
 0.66524585 0.66839786 0.66817664 0.66612508 0.66676093 0.68317884
 0.68061949 0.6864585  0.68729913 0.68350787 0.67885473 0.68832006
 0.68531363 0.68555125 0.68615042 0.69515009 0.69724428 0.70032453
 0.69618203 0.69857424 0.69664204 0.70222295 0.70444917 0.70232206
 0.70253611 0.70123729 0.69896896 0.69720165 0.69712766 0.69677719
 0.71029796 0.70617796 0.70862622 0.7096276  0.71273118 0.70216934
 0.71131573 0.71252028 0.70903367 0.71168081 0.70172489 0.70704184
 0.70170598 0.70239714 0.70330107]


In [ ]:
print(np.max(gs5.cv_results_['mean_test_score'])) 

0.7127311839545515


In [ ]:
print(gs5_best.feature_importances_) # 특성중요도

[0.12098651 0.09502046 0.59281361 0.08709849 0.10408094]


# ⑥Gradient Bossting 회귀 임시 모델링

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

# 그레이디언트부스팅 모델 생성
model_6 = GradientBoostingRegressor()
scores = cross_validate(model_6, train_X_scaled, train_Y, return_train_score=True, n_jobs=-1)

# 마찬가지로 cross_validate로 교차검증을 수행해보면
print('훈련점수:', np.mean(scores['train_score']), '검증점수:', np.mean(scores['test_score']))

훈련점수: 0.971328282076431 검증점수: 0.6829997430327996


In [ ]:
model_6.fit(train_X_scaled, train_Y)
print(model_6.feature_importances_) # 특성중요도

[0.1323486  0.07502901 0.7123666  0.01658431 0.06367148]


그리드서치!

In [ ]:
from sklearn.model_selection import GridSearchCV

params ={'n_estimators':[200, 300, 400, 500, 600, 700], 'max_depth':[3,5,7,9,11], 'learning_rate':[0.01, 0.05, 0.09, 0.13], 'subsample':[0.5, 0.75, 1]} # 하이퍼파라미터 후보들 설정
gs6 = GridSearchCV(GradientBoostingRegressor(), params, n_jobs=-1, cv=4)

In [ ]:
gs6.fit(train_X_scaled, train_Y)

GridSearchCV(cv=4, estimator=GradientBoostingRegressor(), n_jobs=-1,
             param_grid={'learning_rate': [0.01, 0.05, 0.09, 0.13],
                         'max_depth': [3, 5, 7, 9, 11],
                         'n_estimators': [200, 300, 400, 500, 600, 700],
                         'subsample': [0.5, 0.75, 1]})

In [ ]:
gs6.best_params_

{'learning_rate': 0.13, 'max_depth': 3, 'n_estimators': 200, 'subsample': 0.5}

In [ ]:
print(np.max(gs6.cv_results_['mean_test_score'])) 

0.7406332739780435


In [ ]:
gs6_best = gs6.best_estimator_
# GridSearchCV에서는 그 파라미터로 학습한 최적의 모델을 반환해준다!
print(gs6_best.score(train_X_scaled, train_Y))
print(gs6_best.score(test_X_scaled, test_Y))

0.9938050974037416
0.7729845421234892


In [ ]:
print(gs6_best.feature_importances_) # 특성중요도

[0.1887436  0.28521012 0.21706373 0.11984538 0.18913718]


## 히스토그램 기반 GB

In [ ]:
from sklearn.ensemble import HistGradientBoostingRegressor

# 그레이디언트부스팅 모델 생성
model_6_1 = HistGradientBoostingRegressor()
scores = cross_validate(model_6_1, train_X_scaled, train_Y, return_train_score=True, n_jobs=-1)

# 마찬가지로 cross_validate로 교차검증을 수행해보면
print('훈련점수:', np.mean(scores['train_score']), '검증점수:', np.mean(scores['test_score']))

훈련점수: 0.8306799097352722 검증점수: 0.5425105142729592


In [ ]:
model_6.fit(train_X_scaled, train_Y)
print(model_6.feature_importances_) # 특성중요도

[0.18110543 0.32349665 0.26543195 0.11713018 0.11283578]


In [ ]:
from sklearn.model_selection import GridSearchCV

params ={'max_iter':[200, 300, 400, 500, 600, 700], 'max_depth':[3,5,7,9,11], 'learning_rate':[0.01, 0.05, 0.09, 0.13]} # 하이퍼파라미터 후보들 설정
# 주의! 얘는 n_estimators 대신 max_iter 써야함 + subsample 파라미터 없음!
gs6_1 = GridSearchCV(HistGradientBoostingRegressor(), params, n_jobs=-1)

In [ ]:
gs6_1.fit(train_X_scaled, train_Y)

GridSearchCV(estimator=HistGradientBoostingRegressor(), n_jobs=-1,
             param_grid={'learning_rate': [0.01, 0.05, 0.09, 0.13],
                         'max_depth': [3, 5, 7, 9, 11],
                         'max_iter': [200, 300, 400, 500, 600, 700]},
             scoring=make_scorer(mean_squared_error, greater_is_better=False))

In [ ]:
gs6_1.best_params_

{'learning_rate': 0.05, 'max_depth': 3, 'max_iter': 300}

In [ ]:
gs6_1_best = gs6_1.best_estimator_
# GridSearchCV에서는 그 파라미터로 학습한 최적의 모델을 반환해준다!
print(gs6_1_best.score(train_X_scaled, train_Y))
print(gs6_1_best.score(test_X_scaled, test_Y))

0.8503661270838244
0.5900865564401664


# ⑦XGBoost 회귀 임시 모델링

In [ ]:
from xgboost import XGBRegressor

# XGBoost 회귀 모델 생성
model_7 = XGBRegressor(tree_method='hist', random_state=42)
scores = cross_validate(model_7, train_X_scaled, train_Y, return_train_score=True, n_jobs=-1)

# 마찬가지로 cross_validate로 교차검증을 수행해보면
print('훈련점수:', np.mean(scores['train_score']), '검증점수:', np.mean(scores['test_score']))

훈련점수: 0.9999999221359497 검증점수: 0.6432987694430918


In [ ]:
model_7.fit(train_X_scaled, train_Y)
print(model_7.feature_importances_) # 특성중요도

[0.05864235 0.05731633 0.79156995 0.05549662 0.03697471]


그리드서치!

In [ ]:
from sklearn.model_selection import GridSearchCV

params ={'n_estimators':[100, 300, 500, 700, 900], 'max_depth':[3,5,7,9,11], 'learning_rate':[0.01, 0.05, 0.09, 0.13], 'subsample':[0.5, 0.75, 1]} # 하이퍼파라미터 후보들 설정
gs7 = GridSearchCV(XGBRegressor(tree_method='hist'), params, n_jobs=-1, cv=3)

In [ ]:
gs7.fit(train_X_scaled, train_Y)

GridSearchCV(cv=3,
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    feature_types=None, gamma=None, gpu_id=None,
                                    grow_policy=None, importance_type=None,
                                    interaction_constraints=None,
                                    learning_rate=None, m...
                                    max_cat_to_onehot=None, max_delta_step=None,
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None, n_estimators=100,
                                    n_jobs=None, num_parallel_tree=None,
                                    predictor=None, random_state=None, ...),
             n_jobs=-1,
             param_grid={'learning_rate': [0.01, 0.05, 0.09, 0.13],
                         'max_depth': [3, 5, 7, 9, 11],
                         'n_estimators': [100, 300, 500, 700, 900],
                         'subsample': [0.5, 0.75, 1]})

In [ ]:
gs7.best_params_

{'learning_rate': 0.05, 'max_depth': 11, 'n_estimators': 300, 'subsample': 0.5}

In [ ]:
print(gs7.cv_results_['mean_test_score']) # 앙상블이라서 weak model들이네..
print(np.max(gs7.cv_results_['mean_test_score'])) 

[-0.16979885 -0.14390939 -0.15220648  0.57898302  0.58816402  0.58042757
  0.60929673  0.60569746  0.58498105  0.61125847  0.60736785  0.58111458
  0.61166095  0.605686    0.57922694 -0.18808961 -0.16880835 -0.19209181
  0.56999525  0.57859977  0.54110141  0.60910745  0.61092206  0.57520176
  0.61173124  0.61174769  0.56910183  0.61179032  0.61072621  0.56847926
 -0.19036869 -0.17192923 -0.192189    0.56409777  0.56914307  0.53986567
  0.60662645  0.60823447  0.56567709  0.60997196  0.60931322  0.56280975
  0.61016146  0.60904319  0.5603181  -0.19032579 -0.17151432 -0.19181163
  0.56255717  0.56505829  0.53535156  0.60171503  0.60246954  0.5553312
  0.60668762  0.60370219  0.54880181  0.60716931  0.60327686  0.54700894
 -0.19032435 -0.17151432 -0.19181164  0.56281319  0.56436569  0.53517941
  0.60237106  0.60177425  0.54988333  0.60767782  0.60295917  0.54244687
  0.60804174  0.60273676  0.53986295  0.62025435  0.56933504  0.58427751
  0.62250918  0.57726977  0.57854799  0.62038009  0.

In [ ]:
gs7_best = gs7.best_estimator_
# GridSearchCV에서는 그 파라미터로 학습한 최적의 모델을 반환해준다!
print(gs7_best.score(train_X_scaled, train_Y))
print(gs7_best.score(test_X_scaled, test_Y))

0.9997964648628068
0.7773813326540663


In [ ]:
print(gs7_best.feature_importances_) # 특성중요도

[0.06768238 0.08344558 0.63013315 0.11047576 0.10826319]


# ⑧LightGBM 회귀 임시 모델링

In [ ]:
from lightgbm import LGBMRegressor

# LightGBM 회귀 모델 생성
model_8 = LGBMRegressor()
scores = cross_validate(model_8, train_X_scaled, train_Y, return_train_score=True, n_jobs=-1)

# 마찬가지로 cross_validate로 교차검증을 수행해보면
print('훈련점수:', np.mean(scores['train_score']), '검증점수:', np.mean(scores['test_score']))

훈련점수: 0.790561792027834 검증점수: 0.45578801633947813


In [ ]:
model_8.fit(train_X_scaled, train_Y)
print(model_8.feature_importances_) # 특성중요도

[149 156 164 148]
